version: '3.9'

services:
  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://database:3306/airport?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - database
    volumes:
      - .m2:/root/.m2
  database:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: airport
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      DATABASE_HOST: root
